Requisitos-de-Software/2020.2-CarteiraDigitalTransito

docs/planejamento.md

Alterações referentes ao desenvolvimento das metodologias do projeto.
- Adição dos tópicos no documento planejamento.md
- Descrição da metodologia do projeto
#8

#8 Adicionando os tópicos e a descrição das metodologias.

---

docs/planejamento.md

Criação do tópico de introdução na página do Projeto e Definição do cronograma das fases do projeto
[3](https://github.com/Requisitos-de-Software/2020.2-CarteiraDigitalTransito/issues/3)
[6](https://github.com/Requisitos-de-Software/2020.2-CarteiraDigitalTransito/issues/6)

Introdução da página de planejamento e cronograma do projeto

---

docs/planejamento.md

Inclusão da imagem com os horários no planejamento.
- Inclusão dos horários da equipe
- alteração do versionamento do documento
#4

(#4) Inserindo os horários da equipe no documento

---

docs/planejamento.md
docs/pre_rastreabilidade/rich_pictures.md
docs/stylesheets/extra.css

Alterações referentes ao desenvolvimento do artefato Rich Picture.
- Adicionado introdução da Rich Picture;
- Adicionados os diagramas;
- Adicionadas as referências;
- Justificado o texto de toda a wiki.
#2

Adição do Rich Picture na wiki

---

docs/apresentacoes/apresentacao_1.md

Foi adicionado o vídeo a github pages
#13 
- Vídeo adicionado a wiki

13 apresentação

---

README.md
docs/pre_rastreabilidade/rich_pictures.md

README atualizado com o index da wiki e legendas adicionadas seguindo as normas ABNT.
Closes #18 
-  Criação do README.md
-  Adicionado legendas nas imagens, seguindo as normas ABNT

Refinamento da primeira entrega

---

.github/pull_request_template.md
docs/atas/reuniao-26-02-2021.md
mkdocs.yml

Documentação da reunião do dia 26/02/2021
- Adicionada a ata de reunião do dia 26/02/2021
- Atualizado o template de pull request.
#20

Ata da reunião do dia 26/02/2021

---

docs/elicitacao/introspeccao.md

Criação do documento de Introspecção.
Closes #21

Criando Introspecção

---

docs/elicitacao/questionario.md

Foi levantado os requisitos do questionário
#26

26 questionario

---

docs/apresentacoes/apresentacao_2.md

Foi adicionado o link na wiki e enviado o pdf para o moodle
#32

(#32) adição da apresentação 2

---

docs/atas/reuniao-15-03-2021.md
mkdocs.yml

Documentação da reunião de 15/03/2021
-  Adicionada a ata da reunião;
Closes #39

Ata da reunião de 15/03/2021.

---

docs/apresentacoes/apresentacao_2.md
docs/apresentacoes/apresentacao_3.md

Adicionando apresentação 3

---

docs/modelagem/especificacao_suplementar.md

Foi levantado os requisitos com a especificação suplementar
#41

Especificação Suplementar

---

docs/atas/reuniao-23-03-2021.md
mkdocs.yml

Documentação da reunião do dia 23/03/2021
#52

Adicionando ata da reunião do dia 23/03/2021

---

docs/apresentacoes/apresentacao_4.md

Adição apresentação 4

---

docs/analise/verificacao/caso_de_uso.md

Verificação do documento de casos de uso
#72

72 casos de uso

---

docs/analise/verificacao/nfr_framework.md

Documento de NFR

---

docs/analise/verificacao/cenario.md

- TCriação do documento de verificação dos cenários
#73

#73 - cenarios

---

docs/analise/verificacao/planejamento.md
docs/analise/verificacao/rich_picture.md
docs/atas/reuniao-05-04-2021.md
docs/atas/reuniao-23-03-2021.md
mkdocs.yml

Realização do planejamento da Verificação e da verificação do Rich Picture.
- Documentadas as discussões da semana;
- Planejado a Verificação;
- Verificado o Rich Picture.
Closes #68

Planejamento e Rich Picture

---

docs/analise/validacao/viewpoint.md

A técnica é baseada no fato de que os requisitos de software podem e devem ser eliciados de diferentes pontos de vista, e que a avaliação resultante das diferenças deles pode ser usada como uma forma de auxiliar na validação inicial dos requisitos.
Não criado seguindo a estrutura definida na issue mas foi descritos todos os pontos ao longo do documento.

Viewpoints

---

docs/apresentacoes/apresentacao_5.md

#84 Apresentação 5

---

docs/analise/verificacao/backlog.md
docs/elicitacao/requisitos.md
docs/modelagem/backlog_do_produto.md

Foi corrigido os documentos de backlog e de todos os requisitos
#91

Revisão de arquivos

---

docs/analise/verificacao/historia_de_usuario.md
docs/elicitacao/introspeccao.md
docs/modelagem/historia_de_usuario.md

Ajustes nos artefatos de Introspeção e Histórias de Usuário
Realocação da introdução;
Descrição da metodologia;
Historias de Usuário inseridas em uma tabela para facilitar a leitura
Todos os erros apontados na verificação corrigos
[#86]

Revisão dos arquivos Introspeção e Histórias de Usuário

---

docs/pos_rastreabilidade/backward_from.md

Realização da atividade referente a matriz backward from. A rastreabilidade dos casos de uso se referem ao documento refatorado em #90.
- Rastreados os requisitos nos artefatos 
Closes #89

Matriz Backward-from
